---
# Python 3 with MySQL
version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    hostname: nyu
    container_name: nyu
    volumes:
      - ..:/app
    command: sleep infinity
    environment:
      FLASK_APP: service:app
      FLASK_ENV: development
      PORT: 8000
      DATABASE_URI: mysql+mysqldb://root:pass@mysql/db
    networks:
      - dev
    depends_on:
      - mysql

  mysql:
    image: mysql/mysql-server:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306" # Hardcoded here to 3307 because docker-compose in the VS Code Devcontainer setup is run
      # from the users shell on the host OS where the env vars are not yet set
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dev

volumes:
  mysql_data:

networks:
  dev:
